version: '3'
services:
  redis-node-master:
    image: grokzen/redis-cluster:latest
    environment:
      - 'IP=0.0.0.0'
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7002:7002'
      - '7003:7003'
      - '7004:7004'
      - '7005:7005'
